# Generated by Django 2.2.10 on 2020-04-06 04:20

import course.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('intro', models.TextField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.FileField(blank=True, upload_to=course.models.user_directory_path)),
                ('attach', models.FileField(blank=True, upload_to=course.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_user',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-create_time',),
            },
        ),
    ]
